### ISSUE TITLE
build directory less and scss builds contain multiple [object object] lines

### ISSUE THREAD

**Issue by edwinmesmerise** [lukasoppermann/design-token-transformer#47] opened 2023-03-22 17:41 UTC
I'm new to Design Token and Amazon Style Dictionary so I may be pointing out something known but the less and scss builds in the build directory contains multiple [object object] entries, for example:

```
$spacing-10: [object Object];
$spacing-mixed: [object Object];
$spacing-top: [object Object];
$borders-single: [object Object];
$borders-dashed-outside: [object Object];
$borders-single-style: [object Object];
```
I have seen this issue mentioned over the last couple of days while reading documentation, I think it relates to Style Dictionary. There is an issue [here](https://github.com/amzn/style-dictionary/issues/826) in which the post by jam-awake appears to identify the cause and solution in case it helps.

**Comment by edwinmesmerise** [comment] 2023-03-22 17:47
Correction, on re-reading that solution it appears to relate to a config of Tokens Studio, not Style Dictionary, although it may still explain the cause and how they solve it.

**Comment by lukasoppermann** [comment] 2023-04-18 13:04
hey, sorry for the very late reply.

This issue is probably related to some transformers you use.

Style dictionary can not render objects, so they need to be transformed. You need to use the transformers from this repo or build your own, to combine the objects in a way to output a string or number.

For example to create a padding you could use this: https://github.com/lukasoppermann/design-token-transformer/blob/main/src/web/webPadding.js

```js
module.exports = {
  type: 'value',
  matcher: function (token) {
    return token.type === 'custom-spacing'
  },
  transformer: ({ value: { top, left, bottom, right } }) => {
    if ([bottom, left, right].every(v => v === top)) {
      return `${top}px`
    }
    return `${top}px ${right}px ${bottom}px ${left}px`
  }
}
```

**Comment by lukasoppermann** [comment] 2023-05-08 07:39
The problem is that the correct transformers are not loaded. It should be fixed now.

However this is a relatively old workflow. While it works well with the plugin, I would generally recommend to build your won transformations for the plugin based on [style-dictionary-utils](https://github.com/lukasoppermann/style-dictionary-utils).

**Closed by lukasoppermann** 2023-05-08 07:39 UTC
